<?php

namespace App\Api\Core\Helpers;

class StatusCodeHelper
{
    CONST STATUS_OK=200;
    CONST STATUS_CREATED=201;
    CONST STATUS_BAD_REQUEST=400;
    CONST STATUS_NOT_FOUND=404;
    CONST STATUS_UNPROCESSABLE=422;
    CONST INTERNAL_SERVER_ERROR=500;
}
